services:
  postgres:
    image: postgres:16
    container_name: users_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres_test:
    image: postgres:16
    container_name: users_postgres_test
    restart: always
    env_file:
      - .env.test
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    ports:
      - "5454:5432"

  fastapi:
    container_name: users_fastapi
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"

  redis:
    image: redis:latest
    container_name: users_redis
    restart: always
    volumes:
      - ./redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin_auth
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_CONFIG_SERVER_MODE: "${PGADMIN_CONFIG_SERVER_MODE}"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "6060:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G


volumes:
  postgres_data:
  postgres_data_test:
  pgadmin-data:
