services:
  postgres:
    image: postgres:16
    container_name: users_postgres
    restart: always
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  fastapi:
    container_name: users_fastapi
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/src
    ports:
      - "127.0.0.1:8000:8000"

  redis:
    image: redis:latest
    container_name: users_redis
    restart: always
    volumes:
      - ./redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env.prod
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  postgres_data:
