services:
  postgres:
    image: postgres:16
    container_name: users_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    container_name: users_fastapi
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"

  redis:
    image: redis:latest
    container_name: users_redis
    restart: always
    volumes:
      - ./redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env


volumes:
  postgres_data:
